# Site settings
title: Julia Stewart Lowndes, PhD
email: lowndes@nceas.ucsb.edu
url: http://jules32.github.io/
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# Google services https://desiredpersona.com/google-analytics-jekyll/
google_analytics: UA-78110415-1

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Julia Stewart Lowndes, <a href="http://startbootstrap.com">Freelancer theme</a> 
  location: Location
  social: 
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/juliesquid
  - title: github
    url: http://github.com/jules32
  - title: google
    url: https://scholar.google.com/citations?user=qr9gICIAAAAJ&hl=en&authuser=1

# Postal address (add as many lines as necessary)
address:
  - line: NCEAS
  - line: Santa Barbara, California, USA

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty


# image hover: https://github.com/robwierzbowski/jekyll-picture-tag